services:
  genericIO-ioc:
    image: weiss-demo-genericio-ioc
    container_name: genericIO-ioc
    restart: always
    network_mode: host
    tty: true
    build:
      args:
        IOC_DIR: genericIO

  motorSim-ioc:
    image: weiss-demo-motorsim-ioc
    container_name: motorSim-ioc
    restart: always
    network_mode: host
    tty: true
    build:
      args:
        IOC_DIR: motorSim

  ADSim-ioc:
    image: weiss-demo-adsim-ioc
    container_name: ADSim-ioc
    restart: always
    network_mode: host
    tty: true
    build:
      args:
        IOC_DIR: ADSim
